
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '80AB541BC4BFB7E0E532FF219E8EE699'
    
_lr_action_items = {'COUNT':([2,],[5,]),'SYMBOL':([0,2,3,4,5,6,],[2,-5,2,-4,-6,-3,]),'$end':([0,1,2,3,4,5,6,],[-1,0,-5,-2,-4,-6,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'chemical_equation':([0,],[1,]),'species_list':([0,],[3,]),'species':([0,3,],[4,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> chemical_equation","S'",1,None,None,None),
  ('chemical_equation -> <empty>','chemical_equation',0,'p_chemical_equation','test.py',42),
  ('chemical_equation -> species_list','chemical_equation',1,'p_chemical_equation','test.py',43),
  ('species_list -> species_list species','species_list',2,'p_species_list','test.py',52),
  ('species_list -> species','species_list',1,'p_species','test.py',56),
  ('species -> SYMBOL','species',1,'p_single_species','test.py',61),
  ('species -> SYMBOL COUNT','species',2,'p_single_species','test.py',62),
]
